// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csjwgsqnsarvmdvmfwig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzandnc3Fuc2Fydm1kdm1md2lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NjE5MTIsImV4cCI6MjA2NTIzNzkxMn0.rR86HzR9JKFVLIpSfH4n1VGmSye5_9uGKvHP06_Z_fE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);